name: CI
on:
  pull_request:
  push:

jobs:
  test:
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            java: 8
            jobtype: 1
          - os: windows-latest
            java: 8
            jobtype: 2
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}
        cache: sbt
    - name: Build and test (1)
      if: ${{ matrix.jobtype == 1 }}
      shell: bash
      run: |
        sbt -v -Dfile.encoding=UTF-8 -Dsbt.supershell=never "zincScripted/Test/run"
    - name: Build and test (2)
      if: ${{ matrix.jobtype == 2 }}
      shell: bash
      run: |
        sbt -v -Dfile.encoding=UTF-8 -Dsbt.supershell=never "zincScripted/Test/run"
    - name: Build and test (3)
      if: ${{ matrix.jobtype == 3 }}
      shell: bash
      run: |
        sbt -v -Dfile.encoding=UTF-8 scalafmtCheckAll scalafmtSbtCheck
    - name: Benchmark (Scalac) (4)
      if: ${{ matrix.jobtype == 4 }}
      shell: bash
      run: |
        sbt -v -Dfile.encoding=UTF-8 "-Dbenchmark.pattern=.*Scalac.*" "runBenchmarks"
    - name: Benchmark (Shapeless) (5)
      if: ${{ matrix.jobtype == 5 }}
      shell: bash
      run: |
        sbt -v -Dfile.encoding=UTF-8 "-Dbenchmark.pattern=.*Shapeless.*" "runBenchmarks"
    - name: Benchmark (AnalysisFormatBenchmark) (6)
      if: ${{ matrix.jobtype == 6 }}
      shell: bash
      run: |
        sbt -v -Dfile.encoding=UTF-8 "-Dbenchmark.pattern=.*AnalysisFormatBenchmark.*" "runBenchmarks"
    - name: Checkout Target Branch (4-6)
      if: ${{ github.event_name == 'pull_request' && (matrix.jobtype >= 4 || matrix.jobtype <= 6) }}
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.base.ref }}
    - name: Benchmark (Scalac) against Target Branch (4)
      if: ${{ github.event_name == 'pull_request' && matrix.jobtype == 4 }}
      shell: bash
      run: |
        sbt -v -Dfile.encoding=UTF-8 "-Dbenchmark.pattern=.*Scalac.*" "runBenchmarks"
    - name: Benchmark (Shapeless) against Target Branch (5)
      if: ${{ github.event_name == 'pull_request' && matrix.jobtype == 5 }}
      shell: bash
      run: |
        sbt -v -Dfile.encoding=UTF-8 "-Dbenchmark.pattern=.*Shapeless.*" "runBenchmarks"
    - name: Benchmark (AnalysisFormatBenchmark) against Target Branch (6)
      if: ${{ github.event_name == 'pull_request' && matrix.jobtype == 6 }}
      shell: bash
      run: |
        sbt -v -Dfile.encoding=UTF-8 "-Dbenchmark.pattern=.*AnalysisFormatBenchmark.*" "runBenchmarks"
